### ISSUE TITLE
Filter by college

### ISSUE THREAD

**Issue by guilhermeleobas** [dnlcrl/PyScholar#2]
Hi,

Is it possible to get all papers published by a college using PyScholar? If yes, how?

**Comment by dnlcrl** [comment]
Hi Guilherme, 

If you run `scholar.py --help`, you can see all the parameters you can set in your query. Unfortunately there is not a specific option to get all papers published by an institution, because currently Google Scholar doesn't allows you to search by institution. But you can try passing the college name for the author(s) parameter (`-a` or `--author`).
